---
title: "data_experimentation"
author: "Josh Fortin"
date: "2/26/2021"
output: 
  html_document:
    theme: united
    keep_md: TRUE
    toc: TRUE
    df_print: paged
    code_download: true
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(tidyverse)
library(patchwork)
library(lubridate)
library(RColorBrewer)
```

```{r loading data}
Adopted_Capital_Improvement_Budgets <- read_csv("Adopted_Capital_Improvement_Budgets.csv")

Adopted_Capital_Improvement_Budgets %>% 
  mutate(across(where(is.character), as.factor)) %>% 
  summary()
```

```{r}
g_yearly <- Adopted_Capital_Improvement_Budgets %>% 
  group_by(YEAR) %>% 
  summarize(year_amount = sum(Amount)) %>% 
  ggplot(aes(x = YEAR, y = year_amount)) +
  geom_col(fill = "#FDB462") +
  scale_y_continuous(labels = scales::dollar) +
  labs(title = "Yearly Total Adopted CIB",
       subtitle = "2004 - 2021",
       y = "",
       x = "") +
  theme(plot.title.position = "plot",
        plot.background = element_rect("linen"), 
        panel.background = element_rect("linen"),
        legend.background = element_rect("linen"),
        axis.ticks.y = element_blank(),
        panel.grid.major.y = element_line("grey70"),
        panel.grid.minor.y = element_line("grey85"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank())

g_med <- Adopted_Capital_Improvement_Budgets %>% 
  group_by(YEAR) %>% 
  summarize(year_median = median(Amount)) %>% 
  ggplot(aes(x = YEAR, y = year_median)) +
  geom_col(fill = "#FDB462") +
  scale_y_continuous(labels = scales::dollar) +
  labs(title = "Median Adopted CIB Project Cost",
       subtitle = "Per Year: 2004 - 2021",
       y = "",
       x = "") +
  theme(plot.title.position = "plot",
        plot.background = element_rect("linen"), 
        panel.background = element_rect("linen"),
        legend.background = element_rect("linen"),
        axis.ticks.y = element_blank(),
        panel.grid.major.y = element_line("grey70"),
        panel.grid.minor.y = element_line("grey85"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank())

g_mean <- Adopted_Capital_Improvement_Budgets %>% 
  group_by(YEAR) %>% 
  summarize(year_mean = mean(Amount)) %>% 
  ggplot(aes(x = YEAR, y = year_mean)) +
  geom_col(fill = "#FDB462") +
  scale_y_continuous(labels = scales::dollar) +
  labs(title = "Average Adopted CIB Project Cost",
       subtitle = "Per Year 2004 - 2021",
       y = "",
       x = "") +
  theme(plot.title.position = "plot",
        plot.background = element_rect("linen"), 
        panel.background = element_rect("linen"),
        legend.background = element_rect("linen"),
        axis.ticks.y = element_blank(),
        panel.grid.major.y = element_line("grey70"),
        panel.grid.minor.y = element_line("grey85"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank())

g_yearly_counts <- Adopted_Capital_Improvement_Budgets %>% 
  group_by(YEAR) %>% 
  summarize(year_count = n()) %>% 
  ggplot(aes(x = YEAR, y = year_count)) +
  geom_col(fill = "#FDB462") +
  labs(title = "Amount of Adopted CIB Projects",
       subtitle = "Per Year: 2004 - 2021",
       y = "",
       x = "") +
  theme(plot.title.position = "plot",
        plot.background = element_rect("linen"), 
        panel.background = element_rect("linen"),
        legend.background = element_rect("linen"),
        axis.ticks.y = element_blank(),
        panel.grid.major.y = element_line("grey70"),
        panel.grid.minor.y = element_line("grey85"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank())

myplot1 <- ((g_yearly / g_yearly_counts) | (g_mean / g_med)) +
  plot_annotation(title = "Change in the City of Saint Paul's Capital Improvement Budget (CIB) Over Time",
                  caption = "Josh Fortin")

ggsave("final_project_graph_jf.png", myplot1)
```


```{r}
g_yearly_counts <- Adopted_Capital_Improvement_Budgets %>% 
  add_count(SERVICE, name = "counts") %>% 
  group_by(YEAR) %>% 
  summarize(year_count = sum(counts)) %>% 
  ggplot(aes(x = YEAR, y = year_count)) +
  geom_col(fill = "#FDB462") +
  labs(title = "Total Adopted Capital Improvement Budgets Projects per Year",
       subtitle = "2004 - 2021",
       y = "",
       x = "") +
  theme(plot.title.position = "plot",
        plot.background = element_rect("linen"), 
        panel.background = element_rect("linen"),
        legend.background = element_rect("linen"),
        axis.ticks.y = element_blank(),
        panel.grid.major.y = element_line("grey70"),
        panel.grid.minor.y = element_line("grey85"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank())

g_med_counts <- Adopted_Capital_Improvement_Budgets %>% 
  add_count(SERVICE, name = "counts") %>% 
  group_by(YEAR) %>% 
  summarize(year_counts_med = median(counts)) %>% 
  ggplot(aes(x = YEAR, y = year_counts_med)) +
  geom_col(fill = "#FDB462") +
  labs(title = " Median Adopted Capital Improvement Budget Projects per Year",
       subtitle = "2004 - 2021",
       y = "",
       x = "") +
  theme(plot.title.position = "plot",
        plot.background = element_rect("linen"), 
        panel.background = element_rect("linen"),
        legend.background = element_rect("linen"),
        axis.ticks.y = element_blank(),
        panel.grid.major.y = element_line("grey70"),
        panel.grid.minor.y = element_line("grey85"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank())

g_mean_counts <- Adopted_Capital_Improvement_Budgets %>% 
  add_count(SERVICE, name = "counts") %>% 
  group_by(YEAR) %>% 
  summarize(year_mean_counts = mean(counts)) %>% 
  ggplot(aes(x = YEAR, y = year_mean_counts)) +
  geom_col(fill = "#FDB462") +
  labs(title = "Mean Adopted Capital Improvement Budget Projects per Year",
       subtitle = "2004 - 2021",
       y = "",
       x = "") +
  theme(plot.title.position = "plot",
        plot.background = element_rect("linen"), 
        panel.background = element_rect("linen"),
        legend.background = element_rect("linen"),
        axis.ticks.y = element_blank(),
        panel.grid.major.y = element_line("grey70"),
        panel.grid.minor.y = element_line("grey85"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank())

g_yearly_counts | (g_mean_counts / g_med_counts)
```


```{r Projects by Service Type}
g1 <- Adopted_Capital_Improvement_Budgets %>% 
  add_count(SERVICE, name = "counts") %>% 
  mutate(s_reorder = fct_reorder(SERVICE, counts, .fun = max)) %>% 
  ggplot(aes(y = s_reorder)) +
  geom_bar(fill = "#FDB462") +
  labs(title = "Amount of Projects by Service Type",
       x = "",
       y = "") +
  theme(plot.title.position = "plot",
        plot.background = element_rect("linen"), 
        panel.background = element_rect("linen"),
        legend.background = element_rect("linen"),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        panel.grid.major.x = element_line("grey70"),
        panel.grid.minor.x = element_line("grey85"),
        panel.grid.major.y = element_blank())

g2 <- Adopted_Capital_Improvement_Budgets %>% 
  mutate(Service_reorder = fct_reorder(SERVICE, Amount, sum)) %>% 
  ggplot(aes(x = Amount, y = Service_reorder)) +
  geom_col(fill = "#FDB462") +
  labs(title = "Costs of Projects by Service Type",
       x = "",
       y = "") +
  scale_x_continuous(labels = scales::dollar) +
  theme(plot.title.position = "plot",
        plot.background = element_rect("linen"), 
        panel.background = element_rect("linen"),
        legend.background = element_rect("linen"),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        panel.grid.major.x = element_line("grey70"),
        panel.grid.minor.x = element_line("grey85"),
        panel.grid.major.y = element_blank())

service_g <- g1 / g2
service_g
```

```{r projects by department}
g3 <- Adopted_Capital_Improvement_Budgets %>% 
  add_count(DEPARTMENT, name = "counts") %>% 
  mutate(d_reorder = fct_reorder(DEPARTMENT, counts, .fun = max)) %>% 
  ggplot(aes(y = d_reorder)) +
  geom_bar(fill = "#FDB462") +
  labs(title = "Amount of Projects by Department",
       x = "",
       y = "") +
  theme(plot.title.position = "plot",
        plot.background = element_rect("linen"), 
        panel.background = element_rect("linen"),
        legend.background = element_rect("linen"),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        panel.grid.major.x = element_line("grey70"),
        panel.grid.minor.x = element_line("grey85"),
        panel.grid.major.y = element_blank())

g4 <- Adopted_Capital_Improvement_Budgets %>% 
  mutate(department_reorder = fct_reorder(DEPARTMENT, Amount, sum)) %>% 
  ggplot(aes(x = Amount, y = department_reorder)) +
  geom_col(fill = "#FDB462") +
  labs(title = "Costs of Projects by Department",
       x = "",
       y = "") +
  scale_x_continuous(labels = scales::dollar) +
  theme(plot.title.position = "plot",
        plot.background = element_rect("linen"), 
        panel.background = element_rect("linen"),
        legend.background = element_rect("linen"),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        panel.grid.major.x = element_line("grey70"),
        panel.grid.minor.x = element_line("grey85"),
        panel.grid.major.y = element_blank())

 department_g <- g3 / g4
 department_g
```

> telling story with data: how have capital improvement budgets changed overtime?
> change in proportion of service type of projects overtime?
> how many projects per year were over the median value?

```{r}
g_cost <- Adopted_Capital_Improvement_Budgets %>% 
  mutate(department_reorder = fct_reorder(DEPARTMENT, Amount, sum)) %>%
  ggplot(aes(y = DEPARTMENT, x = Amount, fill = SERVICE)) +
  geom_bar(position = "fill", stat = "identity") +
  scale_x_continuous(labels = scales::percent) +
  theme(legend.position = "right",
        legend.direction = "vertical",
        legend.text = element_text(size = 8),
        plot.title.position = "plot",
        plot.background = element_rect("linen"), 
        panel.background = element_rect("linen"),
        legend.background = element_rect("linen"),
        axis.ticks.y = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()) +
  scale_fill_manual(labels = c("Community Facil.", "Internal Serv.", "Resident / Econ Develop.", "Streets / Utilities"), values = c("#FDB462", "#BEBADA","#80B1D3", "#FB8072")) +
  labs(title = "Proportion of Total Costs of Projects per Department by Service Type",
       subtitle = "",
       x = "",
       y = "",
       fill = "")
```


```{r}
g_amount <- Adopted_Capital_Improvement_Budgets %>% 
  add_count(SERVICE, name = "counts") %>%
  mutate(department_reorder = fct_reorder(DEPARTMENT, counts, sum)) %>%
  ggplot(aes(y = DEPARTMENT, x = counts, fill = SERVICE)) +
  geom_bar(position = "fill", stat = "identity") +
  scale_x_continuous(labels = scales::percent) +
  scale_fill_manual(labels = c("Community Facil.", "Internal Serv.", "Resident / Econ Develop.", "Streets / Utilities"), values = c("#FDB462", "#BEBADA","#80B1D3", "#FB8072")) +
  theme(legend.position = "right",
        legend.direction = "vertical",
        plot.title.position = "plot",
        plot.background = element_rect("linen"), 
        panel.background = element_rect("linen"),
        legend.background = element_rect("linen"),
        legend.text = element_text(size = 8),
        axis.ticks.y = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank()) +
  labs(title = "Proportion of Total Number of Projects per Department by Service Type",
       subtitle = "",
       x = "",
       y = "",
       fill = "")
```


```{r}
g_amount / g_cost
```



```{r}
Adopted_Capital_Improvement_Budgets %>% 
  filter(SERVICE == "Community Facilities") %>%
  mutate(department_reorder = fct_reorder(DEPARTMENT, Amount, sum)) %>%
  ggplot(aes(x = YEAR, y = Amount, fill = department_reorder)) +
  geom_bar(position = "fill", stat = "identity") +
  scale_y_continuous(labels = scales::percent) +
  scale_fill_brewer(palette = "Set3") +
  labs(title = "Proportion of Yearly Community Facilities Project Costs by Department",
       x = "",
       y = "",
       fill = "") +
  theme(plot.title.position = "plot",
        plot.background = element_rect("linen"), 
        panel.background = element_rect("linen"),
        legend.background = element_rect("linen"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank())
```

```{r}
Adopted_Capital_Improvement_Budgets %>% 
  filter(DEPARTMENT == c("Fire & Safety Services", "Public Art")) 
```

